### ISSUE TITLE
Reset datasetnr on clear

### ISSUE THREAD

**Issue by PaulObermeier** [auriocus/ukaz#3]
method clear {} {
	$hull delete $selfns
	set plotdata {}
	set zstack {}
	**set datasetnr 0**
	$self RedrawRequest
}

**Comment by auriocus** [comment]
I am not sure why this is needed. What is the reason for this request?
The datasetnr should not be inspected externally, the dataset identifier returned from a plot command should be treated as an opaque handle. That's why it is not reset, so that an old handle from a previous plot does not incidentally refer to a new dataset.

**Comment by PaulObermeier** [comment]
Makes auto selection of colors deterministic.

**Comment by auriocus** [comment]
Fixed
